# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import decimal
from typing import Optional


@dataclasses.dataclass()
class Cell:
    id: int
    hash: str
    hash_input: str
    action: Optional[int]
    max_no_ops: Optional[int]
    initial: bool
    section_index: int
    visits: int
    invalid: bool
    state: memoryview


@dataclasses.dataclass()
class CellScore:
    id: int
    cell_id: int
    epoch: int
    score: decimal.Decimal
    placeholder: bool


@dataclasses.dataclass()
class CellScoreMetric:
    id: int
    epoch: int
    cell_id: int
    min_score: decimal.Decimal
    max_score: decimal.Decimal
    mean_score: decimal.Decimal
    std_score: decimal.Decimal
    visits: int


@dataclasses.dataclass()
class Epoch:
    id: int
    epoch: Optional[int]


@dataclasses.dataclass()
class MaxSection:
    id: int
    section_index: Optional[int]


@dataclasses.dataclass()
class Section:
    name: str
    index: int
